### PR TITLE
add issue correction

### PR DESCRIPTION
**Pull request by loppam**
i feel the typo was the use of the extra "MM" in the format of the dayjs

### CODE REVIEW

**Comment by kaf-lamed-beyt** [comment]
No, that's not it. 

There's nothing wrong with the date. The text is the only thing you should change 😃

This is the outcome of your change 👇🏽

Screenshot_20230112_072839_Chrome


...which shouldn't be, actually. You just need to change the text to "Published". And try to make sure that the builds are not failing. 

One way to do this would be to make sure that you've installed all the dependencies of the project with `npm install` 

I'm sorry, that I haven't updated the README file.

**Comment by loppam** [comment]
Oh wow sorry about that, I felt it would be a technical issue rather than a
text issue. I guess I would be calm and check back to back next time.

**Comment by kaf-lamed-beyt** [comment]
Ayy! 😃🤞🏽

**Comment by loppam** [comment]
This is my new correction.

**Comment by loppam** [comment]
This is my new correction

**Comment by loppam** [comment]
This is my new correction

**Review by kaf-lamed-beyt — APPROVED** [review]
Now, this is great!

**Comment by loppam** [comment]
Thanks chief
Sorry for the earlier error.

**Comment by kaf-lamed-beyt** [comment]
Nah! it is nothing 😃

**Pull request merged**
